name: Build & Publish Mod

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest
    env:
      DLL: "dev.bw.nametag_colour.dll"
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Move Package to Thunderstore dir
        run: |
          cp bin/Release/netstandard2.1/${{env.DLL}} thunderstore/
          cp bin/Release/netstandard2.1/${{env.DLL}} ./
      - name: Bump version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "NametagColour.csproj"
          version: bump-build
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: bwdotdev
          name: NametagColour
          description: Sync the colour of your nametag with the colour of your character
          path: thunderstore
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          version: ${{ steps.bump.outputs.oldVersion }}
          community: repo
          repo: thunderstore.io
          deps: BepInEx-BepInExPack@5.4.2100
          categories: |
            clientside
            misc
            mods
      - name: Create Tag
        run: |
          git tag v${{ steps.bump.outputs.oldVersion }}
          git push origin v${{ steps.bump.outputs.oldVersion }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
          name: ${{ steps.bump.outputs.oldVersion }}
          tag_name: v${{ steps.bump.outputs.oldVersion }}
          files: |
            ${{env.DLL}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push bump
        run: |
          git add NametagColour.csproj
          git commit -m "[skip] ${{ steps.bump.outputs.oldVersion }} -> ${{ steps.bump.outputs.newVersion }}"
          git push origin
